  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop
  
  - name: Recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download {{role_name}} application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/{{role_name}}.zip
      dest: /tmp

  - name: extract {{role_name}} application
    ansible.builtin.unarchive:
      src: /tmp/{{role_name}}.zip
      dest: /app
      remote_src: yes
