  - name: Copy {{role_name}} service
    ansible.builtin.copy:
      src: {{role_name}}.service
      dest: /etc/systemd/system/{{role_name}}.service

  - name: deamon realod and start
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable {{role_name}}
    ansible.builtin.service:
      name: "{{role_name}}"
      state: started
      enabled: yes